### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by UjuiUjuMandan** [james58899/MuzeiPixivSource#305]
Would you like to include this app in F-Droid? I have opened a merge request for it.

- https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15796

Analytics has been removed due to F-Droid's policy.

**Comment by james58899** [comment]
I'd like to publish the app on F-Droid, but I'm not clear on how to satisfy their requirements. It would be nice if you could help.
